version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    #            target: development
    ports:
      - 8080:5173
    volumes:
      - ./app:/app
    # command: npm run serve
    # command: >
    #   ash -c 'npm install; npm run dev'

    tty: true
